---
- name: "prepare ebtables"
  shell: sudo update-alternatives --set ebtables /usr/sbin/ebtables-legacy

- name: "prepare iptables"
  shell: sudo update-alternatives --set iptables /usr/sbin/iptables-legacy

- name: "prepare iptablesv6"
  shell: sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

- name: "prepare arptables"
  shell: sudo update-alternatives --set arptables /usr/sbin/arptables-legacy  
